name: Marketplace
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build-packages:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: darwin
            arch: arm64
            npm_config_arch: arm64
          - os: macos-latest
            platform: darwin
            arch: x64
            npm_config_arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: arm64
            npm_config_arch: arm64
          - os: ubuntu-latest
            platform: linux
            arch: x64
            npm_config_arch: x64
          - os: windows-latest
            platform: win32
            arch: arm64
            npm_config_arch: arm64
          - os: windows-latest
            platform: win32
            arch: x64
            npm_config_arch: x64
    runs-on: ${{ matrix.os }}
    env:
      PIP_ARCH: ${{ matrix.arch }}
      TARGET_NAME: ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: pip install nox
      - run: nox --session setup
      - run: npm install --include=dev
        env:
          npm_config_arch: ${{ matrix.npm_config_arch }}
      - run: npm version $GITHUB_REF_NAME --no-git-tag-version
      - run: npx vsce package --out maccarone-${{ env.TARGET_NAME }}.vsix --target ${{ env.TARGET_NAME }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TARGET_NAME }}
          path: "*.vsix"
  publish-to-marketplace:
    runs-on: ubuntu-latest
    needs: build-packages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
      - run: npm install --include=dev
      - uses: actions/download-artifact@v3
      - run: "./node_modules/@vscode/vsce/vsce publish --packagePath */*.vsix"
        env:
          VSCE_PAT: ${{ secrets.AZURE_DEVOPS_ACCESS_TOKEN }}
